<div class="section widget-category-thumbnail-image category-grid-5 margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('space_between_item') ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $_catCollection = $block->getCatCollection(); ?>
	<?php if ($_catCollection->count()) { ?>
	<div class="row elementor__content d-grid grid-5">
		<?php
			$image_size = [
				['width' => 750, 'height' => 944],
				['width' => 1000, 'height' => 443],
				['width' => 535, 'height' => 478],
				['width' => 535, 'height' => 478],
				['width' => 750, 'height' => 944]
			];
		?>
		<?php $items = 0; foreach ($_catCollection as $_cat) { ?>
			<?php
				$width = $image_size[$items]['width'];
				$height = $image_size[$items]['height'];
			?>
			<div class="bls__collection-column">
				<div class="elementor-category-thumbnail-image-item elementor__item--hover">
					<?php
						$featuredImage = '';
						if($_cat->getData('widget_category_thumbnail') != ''){
							$featuredImage = $block->getCategoryThumnnail($_cat->getData('widget_category_thumbnail'));
						}
						if (!$featuredImage) {
							$featuredImage = '//placehold.jp/1aada3/fff/'.$width.'x'.$height.'.png?text='.$width.'x'.$height;
						}
						$aspect_ratio = $width / $height;
					?>
					<a href="<?= /*@noEscape*/ $_cat->getUrl(); ?>" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: <?= $aspect_ratio;?>;" data-bgset="<?= $block->escapeHtml($featuredImage) ?>" data-sizes="auto">
					</a>
					<div class="category-thumbnail__info absolute center-bottom">
						<h3 class="category-thumbnail__title"><a class="btn category-thumbnail__title_as_button" href="<?= /*@noEscape*/ $_cat->getUrl(); ?>"> <?= /*@noEscape*/ $_cat->getName(); ?> </a></h3>
					</div>
				</div>
			</div>
			<?php $items ++; ?>
		<?php } ?>
		<?php 
			if ($items < 5) {
				$count = $items + 1;
				for ($x = $count; $x <= 5; $x++) { 
					$width = $image_size[$items-1]['width'];
					$height = $image_size[$items-1]['height'];
				?>
					<div class="bls__collection-column">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<?php
								$featuredImage = '//placehold.jp/1aada3/fff/'.$width.'x'.$height.'.png?text='.$width.'x'.$height;
								$aspect_ratio = $width / $height;
							?>
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: <?= $aspect_ratio;?>;" data-bgset="<?= $block->escapeHtml($featuredImage) ?>" data-sizes="auto">
							</a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a class="btn category-thumbnail__title_as_button" href="#"> Watches </a></h3>
							</div>
						</div>
					</div>
			<?php	}
		?>
		<?php } ?>
	</div>
	<?php }else{ ?>
		<div class="row elementor__content">
			<div class="col-md-6 col-12">
				<div class="elementor-category-thumbnail-image-item elementor__item--hover">
					<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.30164;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-cloth_1.png" data-sizes="auto"> </a>
					<div class="category-thumbnail__info absolute center-bottom">
						<h3 class="category-thumbnail__title"><a href="#" class="btn category-thumbnail__title_as_button"> Watches </a></h3>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-12 has-children">
				<div class="row row-level-2">
					<div class="col-md-12 col-6">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.31724;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-watch_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#" class="btn category-thumbnail__title_as_button"> Watches </a></h3>
							</div>
						</div>
					</div>
					<div class="col-md-12 col-6">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.31724;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-cloth_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#" class="btn category-thumbnail__title_as_button"> Watches </a></h3>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-12 has-children">
				<div class="row row-level-2">
					<div class="col-md-12 col-6">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.31724;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-shoes_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#" class="btn category-thumbnail__title_as_button"> Watches </a></h3>
							</div>
						</div>
					</div>
					<div class="col-md-12 col-6">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.31724;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#" class="btn category-thumbnail__title_as_button"> Watches </a></h3>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>


	<?php } ?>
</div>