<div class="section widget-blog-posts-slider-carousel7 margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('margin_item') ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $_postCollection = $block->getPostCollection(); ?>
	<?php if ($_postCollection->count()) { ?>
	<div class="elementor__content widget-blog-post-slider first-loading-slick">
	<?php $data_sizes = $block->getSizeThumbnail(); ?>
	<?php $items = 0; foreach ($_postCollection as $_post) { $items ++; ?>
		<?php
            $_postUrl = $block->escapeUrl($_post->getPostUrl());
            $_postName = $block->escapeHtml($_post->getTitle());
        ?>
		<div class="elementor-blog-post-item">
			<?php
			$featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage();
			$width = 1920;
			$height = 1039;
            if(isset($data_sizes['common']['img'])){
            	$width = $data_sizes['common']['img']['width'];
            	$height = $data_sizes['common']['img']['height'];
            }
            if(isset($data_sizes['custom']['img1'])){
        		$width = $data_sizes['custom']['img1']['width'];
        		$height = $data_sizes['custom']['img1']['height'];
        	}
            if (!$featuredImage) {
            	$featuredImage = '//placehold.jp/1aada3/fff/'.$width.'x'.$height.'.png?text=Minimog';
            }
            $aspect_ratio = $width / $height;
            ?>
			<div class="post-image elementor__item--hover">
				<div class="data-bgset-image-wrapper lazyload" data-bgset="<?= $block->escapeHtml($featuredImage) ?>" data-sizes="auto" style="--aspect-ratio: <?= $aspect_ratio;?>;">
					<a class="item-link" href="<?= /*@noEscape*/ $_postUrl ?>"></a>
				</div>
			</div>
			<div class="post-content">
				<div class="post-info">
					<?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
						<div class="item post-categories">
							<?php $n = 0; ?>
							<?php foreach ($_post->getParentCategories() as $ct) { ?>
								<?php $n++; ?>
								<a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
								href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
								><?= $block->escapeHtml($ct->getTitle()) ?></a><?= /*@noEscape*/ ($n != $_categoriesCount) ? ',' : '' ?>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
				<div class="post-info">
			
					<div class="post-title">
						<a class="post-item-link"
							href="<?= /*@noEscape*/ $_postUrl ?>">
							<?= /*@noEscape*/ $_postName ?>
						</a>
					</div>
					<div class="post-description">
						<?= /*@noEscape*/ $block->getShorContent($_post) ?>
					</div>
					<div class="post-info d-flex align-items-center flex-wrap">
						<?php if ($_post->isPublishDateEnabled()) { ?>
							<div class="item post-posed-date">
								<span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
							</div>
						<?php } ?>
						<?php if ($block->authorEnabled()) { ?>
							<?php if ($_author = $_post->getAuthor()) { ?>
							<div class="item post-author">
								<span class="label"><?= $block->escapeHtml(__('By')) ?></span>
								<span class="value">
								<?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
								<a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
								href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
								<?php } ?>

								<?= $block->escapeHtml($_author->getTitle()) ?>

								<?php if ($authorPageEnabled) { ?>
								</a>
								<?php } ?>
								</span>
							</div>
							<?php } ?>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
	<?php } ?>
	</div>
	<?php }else{ ?>
	<div class="message info empty">
        <div><?= $escaper->escapeHtml(__('No blog posts were found matching your condition.')) ?></div>
    </div>
	<?php } ?>
</div>